# --------------------------------------------
# define the steps we want to run
# --------------------------------------------
steps:
  # ------------------------------------------
  # check out files tracked by git
  # ------------------------------------------
  - name: Checkout
    uses: actions/checkout@v4

  # ------------------------------------------
  # set up pnpm (no internal cache)
  # ------------------------------------------
  - name: Setup pnpm
    uses: pnpm/action-setup@v4
    with:
      version: latest

  # ------------------------------------------
  # find node version
  # ------------------------------------------
  - name: Determine node version
    id: nvm
    run: |
      if [ -f .nvmrc ]; then
        echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      fi

  # ------------------------------------------
  # setup node.js (disable built-in cache)
  # ------------------------------------------
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: ${{ steps.nvm.outputs.NVMRC }}
      cache: 'none'

  # ------------------------------------------
  # manual pnpm store cache (safe-fail on 503)
  # ------------------------------------------
  - name: Cache pnpm store
    uses: actions/cache@v4
    with:
      path: ~/.pnpm-store
      key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        ${{ runner.os }}-pnpm-store-
    continue-on-error: true

  # ------------------------------------------
  # install dependencies
  # ------------------------------------------
  - name: Install dependencies
    run: pnpm install

  # ------------------------------------------
  # check formatting
  # ------------------------------------------
  - name: Run formatter
    run: pnpm format

  # ------------------------------------------
  # check linting
  # ------------------------------------------
  - name: Run linter
    run: pnpm lint

  # ------------------------------------------
  # run unit tests
  # ------------------------------------------
  - name: Run unit tests
    run: pnpm test

  # ------------------------------------------
  # build assets
  # ------------------------------------------
  - name: Build assets
    run: pnpm build
