--- # ------------------------------------------------
# ------------------------------------------------
# test workflow
name: Test

# ------------------------------------------------
# this workflow will run
# • anytime a commit is made to `in-progress`
# • anytime a pull request is opened against main
# ------------------------------------------------
on:
  push:
    branches:
      - 'in-progress'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    # --------------------------------------------
    # workflow runs on an ubuntu image
    # --------------------------------------------
    runs-on: ubuntu-latest

    # --------------------------------------------
    # define the steps we want to run
    # --------------------------------------------
    steps:
      # ------------------------------------------
      # check out files tracked by git
      # ------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------
      # set up pnpm
      # ------------------------------------------
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      # ------------------------------------------
      # find node version
      # ------------------------------------------
      - name: Determine node version
        run: test -f .nvmrc && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      # ------------------------------------------
      # setup node env (no cache to avoid 503)
      # ------------------------------------------
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      # ------------------------------------------
      # install dependencies
      # ------------------------------------------
      - name: Install dependencies
        run: pnpm install

      # ------------------------------------------
      # check formatting
      # ------------------------------------------
      - name: Run formatter
        run: pnpm format

      # ------------------------------------------
      # check linting
      # ------------------------------------------
      - name: Run linter
        run: pnpm lint

      # ------------------------------------------
      # run unit tests
      # ------------------------------------------
      - name: Run unit tests
        run: pnpm test

      # ------------------------------------------
      # build assets
      # ------------------------------------------
      - name: Build assets
        run: pnpm build
