name: Test
on:
  push:
    branches:
      - in-progress
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4

      # determine node version
      - name: Determine node version
        id: nvm
        run: |
          if [ -f .nvmrc ]; then
            echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
          fi

      # setup node (no built-in cache)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'none'

      # install pnpm manually (avoids pnpm/action‐setup caching)
      - name: Install pnpm
        run: npm install -g pnpm@latest

      # install deps & run tasks
      - name: Install dependencies
        run: pnpm install

      - name: Run formatter
        run: pnpm format

      - name: Run linter
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build assets
        run: pnpm build
