--- # ------------------------------------------------
# ------------------------------------------------
# test workflow
name: Test

on:
  push:
    branches:
      - 'in-progress'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04  # Use specific version to avoid cache issues

    steps:
      # Use git directly instead of actions/checkout
      - name: Checkout code
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} .
          git checkout ${{ github.sha }}

      # Rest of your workflow using manual Node setup
      - name: Determine node version
        run: test -f .nvmrc && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup Node.js manually
        run: |
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install ${{ steps.nvm.outputs.NVMRC }}
          nvm alias default ${{ steps.nvm.outputs.NVMRC }}
          echo "$HOME/.nvm/versions/node/v${{ steps.nvm.outputs.NVMRC }}/bin" >> $GITHUB_PATH

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Run formatter
        run: pnpm format

      - name: Run linter
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build assets
        run: pnpm build
