name: Test
on:
  push:
    branches: [ in-progress ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------
      # checkout repository
      # ------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------
      # read Node version from .nvmrc
      # ------------------------------------------
      - name: Determine node version
        id: nvm
        run: |
          echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      # ------------------------------------------
      # setup Node.js (disable internal cache)
      # ------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'none'

      # ------------------------------------------
      # cache pnpm store (safe-fail on 503)
      # ------------------------------------------
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
        continue-on-error: true

      # ------------------------------------------
      # install pnpm and dependencies
      # ------------------------------------------
      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      # ------------------------------------------
      # run tasks
      # ------------------------------------------
      - name: Run formatter
        run: pnpm format

      - name: Run linter
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build assets
        run: pnpm build
