--- # ------------------------------------------------
# ------------------------------------------------
# test workflow
name: Test

# ------------------------------------------------
# this workflow will run
# • anytime a commit is made to `in-progress`
# • anytime a pull request is opened against main
# ------------------------------------------------
on:
  push:
    branches:
      - 'in-progress'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    # --------------------------------------------
    # workflow runs on an ubuntu image
    # --------------------------------------------
    runs-on: ubuntu-latest

    # --------------------------------------------
    # define the steps we want to run
    # --------------------------------------------
    steps:
      # ------------------------------------------
      # check out files tracked by git (minimal)
      # ------------------------------------------
      - name: Checkout
        uses: actions/checkout@v3

      # ------------------------------------------
      # find node version
      # ------------------------------------------
      - name: Determine node version
        run: test -f .nvmrc && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      # ------------------------------------------
      # setup using fnm (faster alternative to nvm)
      # ------------------------------------------
      - name: Setup Node.js via fnm
        run: |
          curl -fsSL https://fnm.vercel.app/install | bash
          export PATH="$HOME/.fnm:$PATH"
          eval "$(fnm env --use-on-cd)"
          fnm install ${{ steps.nvm.outputs.NVMRC }}
          fnm use ${{ steps.nvm.outputs.NVMRC }}
          echo "$HOME/.fnm/node-versions/v${{ steps.nvm.outputs.NVMRC }}/installation/bin" >> $GITHUB_PATH

      # ------------------------------------------
      # verify node and install pnpm
      # ------------------------------------------
      - name: Setup pnpm
        run: |
          node --version
          npm install -g pnpm@latest

      # ------------------------------------------
      # install dependencies
      # ------------------------------------------
      - name: Install dependencies
        run: pnpm install

      # ------------------------------------------
      # check formatting
      # ------------------------------------------
      - name: Run formatter
        run: pnpm format

      # ------------------------------------------
      # check linting
      # ------------------------------------------
      - name: Run linter
        run: pnpm lint

      # ------------------------------------------
      # run unit tests
      # ------------------------------------------
      - name: Run unit tests
        run: pnpm test

      # ------------------------------------------
      # build assets
      # ------------------------------------------
      - name: Build assets
        run: pnpm build
