--- # ------------------------------------------------
# ------------------------------------------------
# test workflow
name: Test

# ------------------------------------------------
# this workflow will run
# • anytime a commit is made to `in-progress`
# • anytime a pull request is opened against main
# ------------------------------------------------
on:
  push:
    branches:
      - 'in-progress'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    # --------------------------------------------
    # workflow runs on an ubuntu image
    # --------------------------------------------
    runs-on: ubuntu-latest

    # --------------------------------------------
    # define the steps we want to run
    # --------------------------------------------
    steps:
      # ------------------------------------------
      # check out files tracked by git
      # ------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------
      # find node version
      # ------------------------------------------
      - name: Determine node version
        run: test -f .nvmrc && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      # ------------------------------------------
      # install node manually using nvm
      # ------------------------------------------
      - name: Install Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install ${{ steps.nvm.outputs.NVMRC }}
          nvm use ${{ steps.nvm.outputs.NVMRC }}
          echo "$HOME/.nvm/versions/node/v${{ steps.nvm.outputs.NVMRC }}/bin" >> $GITHUB_PATH

      # ------------------------------------------
      # install pnpm
      # ------------------------------------------
      - name: Install pnpm
        run: npm install -g pnpm@latest

      # ------------------------------------------
      # install dependencies
      # ------------------------------------------
      - name: Install dependencies
        run: pnpm install

      # ------------------------------------------
      # check formatting
      # ------------------------------------------
      - name: Run formatter
        run: pnpm format

      # ------------------------------------------
      # check linting
      # ------------------------------------------
      - name: Run linter
        run: pnpm lint

      # ------------------------------------------
      # run unit tests
      # ------------------------------------------
      - name: Run unit tests
        run: pnpm test

      # ------------------------------------------
      # build assets
      # ------------------------------------------
      - name: Build assets
        run: pnpm build
