# validate json workflow
name: Validate JSON

# ------------------------------------------------
# this workflow will run
# • anytime a PR is opened against "main"
# ------------------------------------------------
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    # --------------------------------------------
    # workflow runs on an ubuntu image
    # --------------------------------------------
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------
      # check out files tracked by git
      # ------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------
      # determine Node version from .nvmrc
      # ------------------------------------------
      - name: Determine node version
        id: nvm
        run: |
          if [ -f .nvmrc ]; then
            echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
          fi

      # ------------------------------------------
      # setup Node.js (no cache)
      # ------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      # ------------------------------------------
      # install pnpm manually (avoids action‐setup caching)
      # ------------------------------------------
      - name: Install pnpm
        run: npm install -g pnpm@latest

      # ------------------------------------------
      # install dependencies
      # ------------------------------------------
      - name: Install dependencies
        run: pnpm install

      # ------------------------------------------
      # run validation
      # ------------------------------------------
      - name: Run validation
        run: pnpm validate
