# validate json workflow
name: Validate JSON

# ------------------------------------------------
# this workflow will run
# • anytime a PR is opened against "main"
# ------------------------------------------------
on:
  pull_request:
    branches:
      - 'main'

jobs:
  validate:
    # --------------------------------------------
    # workflow runs on an ubuntu image
    # --------------------------------------------
    runs-on: ubuntu-latest

    # --------------------------------------------
    # define the steps we want to run
    # --------------------------------------------
    steps:
      # ------------------------------------------
      # check out files tracked by git
      # ------------------------------------------
      - name: Checkout
        uses: actions/checkout@v3

      # ------------------------------------------
      # set up pnpm
      # ------------------------------------------
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      # ------------------------------------------
      # find node version
      # ------------------------------------------
      - name: Determine node version
        run: test -f .nvmrc && echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      # ------------------------------------------
      # setup node env
      # ------------------------------------------
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'pnpm'

      # ------------------------------------------
      # install dependencies
      # ------------------------------------------
      - name: Install dependencies
        run: pnpm install

      # ------------------------------------------
      # run validation
      # ------------------------------------------
      - name: Run validation
        run: pnpm validate
